on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: yarn test-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install  --network-concurrency 1
      - run: yarn test-all
